name: 'Setup Haxe environment'
description: 'Setup a Haxe environment and add it to the PATH'
author: 'Sho Kuroda <krdlab@gmail.com>'
inputs:
  haxe-version:
    description: 'Version Spec of the version to use. Example: 4.3.1'
    required: true
    default: '4.3.1'
  cache-dependency-path:
    description: 'Used to specify the path to a dependency file.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
branding:
  icon: 'download'
  color: 'gray-dark'
